# Generated by Django 5.2.5 on 2026-05-12 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(help_text='ID команди з tournament-service')),
                ('github_url', models.URLField(blank=True, help_text='Посилання на GitHub репозиторій', null=True)),
                ('video_url', models.URLField(blank=True, help_text='Посилання на відео презентацію', null=True)),
                ('live_demo_url', models.URLField(blank=True, help_text='Посилання на live demo', null=True)),
                ('description', models.TextField(blank=True, help_text='Описання рішення та підходу')),
                ('is_locked', models.BooleanField(default=False, help_text='Чи заблокована від редагування')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_at', models.DateTimeField(blank=True, help_text='Коли була заблокована', null=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.IntegerField(help_text='ID турніру')),
                ('team_id', models.IntegerField(help_text='ID команди')),
                ('total_score', models.FloatField(default=0.0, help_text='Сумарна оцінка команди')),
                ('rank', models.IntegerField(default=0, help_text='Місце в турнірі')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['tournament_id', 'rank'], name='submissions_tournam_6e4c11_idx')],
                'unique_together': {('tournament_id', 'team_id')},
            },
        ),
        migrations.CreateModel(
            name='JuryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jury_user_id', models.IntegerField(help_text='ID користувача журі')),
                ('is_evaluated', models.BooleanField(default=False, help_text='Чи оцінена подача журі')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(help_text='Подача для оцінювання', on_delete=django.db.models.deletion.CASCADE, related_name='jury_assignments', to='submissions.submission')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.IntegerField(help_text='ID турніру з tournament-service')),
                ('created_by', models.IntegerField(help_text='ID користувача який створив')),
                ('title', models.CharField(help_text='Назва завдання', max_length=255)),
                ('description', models.TextField(help_text='Детальний опис завдання')),
                ('tech_requirements', models.JSONField(blank=True, default=dict, help_text='Технічні вимоги до проекту')),
                ('start_time', models.DateTimeField(help_text="Коли розпочнути розв'язування")),
                ('deadline', models.DateTimeField(help_text='Дедлайн для подачи')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['deadline'],
                'indexes': [models.Index(fields=['tournament_id', 'status'], name='submissions_tournam_e8606c_idx'), models.Index(fields=['deadline'], name='submissions_deadlin_7f40f0_idx')],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(help_text='Завдання для якого подача', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='submissions.task'),
        ),
        migrations.CreateModel(
            name='TaskRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Текст вимоги', max_length=255)),
                ('is_required', models.BooleanField(default=True, help_text="Чи обов'язкова вимога")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(help_text='Завдання якому належить вимога', on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='submissions.task')),
            ],
            options={
                'ordering': ['-is_required', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend_code', models.IntegerField(default=0, help_text='Оцінка за backend код (0-100)')),
                ('database', models.IntegerField(default=0, help_text='Оцінка за архітектуру БД (0-100)')),
                ('frontend_code', models.IntegerField(default=0, help_text='Оцінка за frontend (0-100)')),
                ('functionality', models.IntegerField(default=0, help_text='Оцінка за функціональність (0-100)')),
                ('usability', models.IntegerField(default=0, help_text='Оцінка за UX/UI (0-100)')),
                ('comment', models.TextField(blank=True, help_text='Коментар журі')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(help_text='Призначення журі', on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='submissions.juryassignment')),
            ],
            options={
                'ordering': ['-evaluated_at'],
                'unique_together': {('assignment',)},
            },
        ),
        migrations.AddIndex(
            model_name='juryassignment',
            index=models.Index(fields=['jury_user_id', 'is_evaluated'], name='submissions_jury_us_51e926_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='juryassignment',
            unique_together={('submission', 'jury_user_id')},
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['task', 'team_id'], name='submissions_task_id_c113d4_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['is_locked'], name='submissions_is_lock_634d77_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('task', 'team_id')},
        ),
        migrations.AlterUniqueTogether(
            name='taskrequirement',
            unique_together={('task', 'title')},
        ),
    ]
