# Generated by Django 5.2.13 on 2026-05-03 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tournament_id', models.IntegerField(db_index=True, verbose_name='ID турніру')),
                ('name', models.CharField(max_length=100, verbose_name='Назва команди')),
                ('captain_name', models.CharField(max_length=100, verbose_name="Ім'я капітана")),
                ('captain_email', models.EmailField(max_length=254, verbose_name='Email капітана')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Місто')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='Контактний месенджер')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команди',
                'ordering': ['-registered_at'],
                'unique_together': {('tournament_id', 'captain_email')},
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team')),
            ],
            options={
                'verbose_name': 'Учасник команди',
                'verbose_name_plural': 'Учасники команди',
            },
        ),
    ]
